services:
  email-assistant:
    build:
      context: ./email-assistant
      dockerfile: Dockerfile
    env_file:
      - ./email-assistant/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - sendit-network

  email-consumer:
    build:
      context: ./sendit-email-consumer
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - sendit-network

  redis:
    build:
      context: ./redis-server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - sendit-network

networks:
  sendit-network:
    driver: bridge
