services:
  sendit-server:
    build:
      context: ./sendit-server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - sendit-network

  sendit-email-consumer:
    build:
      context: ./sendit-email-consumer
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - sendit-network

networks:
  sendit-network:
    driver: bridge
